# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_EH_transfer', [dirname(__file__)])
        except ImportError:
            import _EH_transfer
            return _EH_transfer
        if fp is not None:
            try:
                _mod = imp.load_module('_EH_transfer', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _EH_transfer = swig_import_helper()
    del swig_import_helper
else:
    import _EH_transfer
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class floatArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, floatArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, floatArray, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _EH_transfer.new_floatArray(nelements)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _EH_transfer.delete_floatArray
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _EH_transfer.floatArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _EH_transfer.floatArray___setitem__(self, index, value)

    def cast(self):
        return _EH_transfer.floatArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _EH_transfer.floatArray_frompointer
    if _newclass:
        frompointer = staticmethod(_EH_transfer.floatArray_frompointer)
floatArray_swigregister = _EH_transfer.floatArray_swigregister
floatArray_swigregister(floatArray)

def floatArray_frompointer(t):
    return _EH_transfer.floatArray_frompointer(t)
floatArray_frompointer = _EH_transfer.floatArray_frompointer


def TFfit_hmpc(omega0, f_baryon, hubble, Tcmb, numk, k, tf_full):
    return _EH_transfer.TFfit_hmpc(omega0, f_baryon, hubble, Tcmb, numk, k, tf_full)
TFfit_hmpc = _EH_transfer.TFfit_hmpc
# This file is compatible with both classic and new-style classes.


