import zeldovich as z
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import library as lb
GridSize = 40
r1=15
r2=5
r3=0.1
a = z.zeldovich(GridSize, XSize = 0.0000064,Seed = 300000)
b = z.zeldovich(GridSize, XSize = 0.256,Seed = 400000)
c = z.zeldovich(GridSize, XSize = 512,Seed = 500000)
Position = a.Position(RedShift=r1 )
fig=plt.figure(figsize=(15,15), dpi= 100, facecolor='w', edgecolor='k')
Xposition=Position[0,:,:,:].reshape((GridSize*GridSize*GridSize))
Yposition=Position[1,:,:,:].reshape((GridSize*GridSize*GridSize))
Zposition=Position[2,:,:,:].reshape((GridSize*GridSize*GridSize))
ax1 = fig.add_subplot(4,3,1, projection='3d')
ax1.scatter(Xposition,Yposition,Zposition,s=0.006,color='#191970')
ax1.view_init(elev=20., azim=30)
ax1.set_xticks([])
ax1.set_yticks([])
ax1.set_zticks([])
ax1.set_xlim3d(np.amin(Xposition),np.amax(Xposition))
ax1.set_ylim3d(np.amin(Yposition),np.amax(Yposition))
ax1.set_zlim3d(np.amin(Zposition),np.amax(Zposition))
ax1.set_ylabel(" 6.4 pc/h",fontsize=13,labelpad=-15)
ax1.set_zlabel("Red Shift = 15 ",fontsize=15,labelpad=-1)


Position = a.Position(RedShift=r2)
Xposition=Position[0,:,:,:].reshape((GridSize*GridSize*GridSize))
Yposition=Position[1,:,:,:].reshape((GridSize*GridSize*GridSize))
Zposition=Position[2,:,:,:].reshape((GridSize*GridSize*GridSize))
ax2 = fig.add_subplot(4,3,4, projection='3d')
ax2.scatter(Xposition,Yposition,Zposition,s=0.009,color='#191970')
ax2.view_init(elev=20., azim=30)
ax2.set_xticks([])
ax2.set_yticks([])
ax2.set_zticks([])
ax2.set_xlim3d(np.amin(Xposition),np.amax(Xposition))
ax2.set_ylim3d(np.amin(Yposition),np.amax(Yposition))
ax2.set_zlim3d(np.amin(Zposition),np.amax(Zposition))
ax2.set_ylabel(" 0.64 pc/h",fontsize=13,labelpad=-15)
ax2.set_zlabel("Red Shift = 5 ",fontsize=15,labelpad=-1)

Position = a.Position(RedShift=r3)
Xposition=Position[0,:,:,:].reshape((GridSize*GridSize*GridSize))
Yposition=Position[1,:,:,:].reshape((GridSize*GridSize*GridSize))
Zposition=Position[2,:,:,:].reshape((GridSize*GridSize*GridSize))
ax3 = fig.add_subplot(4,3,7, projection='3d')
ax3.scatter(Xposition,Yposition,Zposition,s=0.009,color='#191970')
ax3.view_init(elev=20., azim=30)
ax3.set_xticks([])
ax3.set_yticks([])
ax3.set_zticks([])
ax3.set_xlim3d(np.amin(Xposition),np.amax(Xposition))
ax3.set_ylim3d(np.amin(Yposition),np.amax(Yposition))
ax3.set_zlim3d(np.amin(Zposition),np.amax(Zposition))
ax3.set_ylabel(" 0.64 pc/h",fontsize=13,labelpad=-15)
ax3.set_zlabel("Red Shift = 0.1 ",fontsize=15,labelpad=-1)

Position = b.Position(RedShift=r1)
Xposition=Position[0,:,:,:].reshape((GridSize*GridSize*GridSize))
Yposition=Position[1,:,:,:].reshape((GridSize*GridSize*GridSize))
Zposition=Position[2,:,:,:].reshape((GridSize*GridSize*GridSize))
ax4= fig.add_subplot(4,3,2, projection='3d')
ax4.scatter(Xposition,Yposition,Zposition,s=0.009, color='#2c0a33')
ax4.view_init(elev=20., azim=30)
ax4.set_xticks([])
ax4.set_yticks([])
ax4.set_zticks([])
ax4.set_xlim3d(np.amin(Xposition),np.amax(Xposition))
ax4.set_ylim3d(np.amin(Yposition),np.amax(Yposition))
ax4.set_zlim3d(np.amin(Zposition),np.amax(Zposition))
ax4.set_ylabel(" 0.256 Mpc/h",fontsize=13,labelpad=-15)


Position = b.Position(RedShift=r2)
Xposition=Position[0,:,:,:].reshape((GridSize*GridSize*GridSize))
Yposition=Position[1,:,:,:].reshape((GridSize*GridSize*GridSize))
Zposition=Position[2,:,:,:].reshape((GridSize*GridSize*GridSize))
ax5= fig.add_subplot(4,3,5, projection='3d')
ax5.scatter(Xposition,Yposition,Zposition,s=0.009, color='#2c0a33')
ax5.view_init(elev=20., azim=30)
ax5.set_xticks([])
ax5.set_yticks([])
ax5.set_zticks([])
ax5.set_xlim3d(np.amin(Xposition),np.amax(Xposition))
ax5.set_ylim3d(np.amin(Yposition),np.amax(Yposition))
ax5.set_zlim3d(np.amin(Zposition),np.amax(Zposition))
ax5.set_ylabel(" 0.256 Mpc/h",fontsize=13,labelpad=-15)

Position = b.Position(RedShift=r3)
Xposition=Position[0,:,:,:].reshape((GridSize*GridSize*GridSize))
Yposition=Position[1,:,:,:].reshape((GridSize*GridSize*GridSize))
Zposition=Position[2,:,:,:].reshape((GridSize*GridSize*GridSize))
ax6= fig.add_subplot(4,3,8, projection='3d')
ax6.scatter(Xposition,Yposition,Zposition,s=0.009, color='#2c0a33')
ax6.view_init(elev=20., azim=30)
ax6.set_xticks([])
ax6.set_yticks([])
ax6.set_zticks([])
ax6.set_xlim3d(np.amin(Xposition),np.amax(Xposition))
ax6.set_ylim3d(np.amin(Yposition),np.amax(Yposition))
ax6.set_zlim3d(np.amin(Zposition),np.amax(Zposition))
ax6.set_ylabel("0.256 Mpc/h",fontsize=13,labelpad=-15)

Position = c.Position(RedShift=r1)
Xposition=Position[0,:,:,:].reshape((GridSize*GridSize*GridSize))
Yposition=Position[1,:,:,:].reshape((GridSize*GridSize*GridSize))
Zposition=Position[2,:,:,:].reshape((GridSize*GridSize*GridSize))
ax7= fig.add_subplot(4,3,3, projection='3d')
ax7.scatter(Xposition,Yposition,Zposition,s=0.009,color='#2f4f4f')
ax7.view_init(elev=20., azim=30)
ax7.set_xticks([])
ax7.set_yticks([])
ax7.set_zticks([])
ax7.set_xlim3d(np.amin(Xposition),np.amax(Xposition))
ax7.set_ylim3d(np.amin(Yposition),np.amax(Yposition))
ax7.set_zlim3d(np.amin(Zposition),np.amax(Zposition))
ax7.set_ylabel("512 Mpc/h",fontsize=13,labelpad=-15)

Position = c.Position(RedShift=r2)
Xposition=Position[0,:,:,:].reshape((GridSize*GridSize*GridSize))
Yposition=Position[1,:,:,:].reshape((GridSize*GridSize*GridSize))
Zposition=Position[2,:,:,:].reshape((GridSize*GridSize*GridSize))
ax8= fig.add_subplot(4,3,6, projection='3d')
ax8.scatter(Xposition,Yposition,Zposition,s=0.009,color='#2f4f4f')
ax8.view_init(elev=20., azim=30)
ax8.set_xticks([])
ax8.set_yticks([])
ax8.set_zticks([])
ax8.set_xlim3d(np.amin(Xposition),np.amax(Xposition))
ax8.set_ylim3d(np.amin(Yposition),np.amax(Yposition))
ax8.set_zlim3d(np.amin(Zposition),np.amax(Zposition))
ax8.set_ylabel(" 512 Mpc/h",fontsize=13,labelpad=-15)

Position = c.Position(RedShift=r3)
Xposition=Position[0,:,:,:].reshape((GridSize*GridSize*GridSize))
Yposition=Position[1,:,:,:].reshape((GridSize*GridSize*GridSize))
Zposition=Position[2,:,:,:].reshape((GridSize*GridSize*GridSize))
ax9= fig.add_subplot(4,3,9, projection='3d')
ax9.scatter(Xposition,Yposition,Zposition,s=0.009,color='#2f4f4f')
ax9.view_init(elev=20., azim=30)
ax9.set_xticks([])
ax9.set_yticks([])
ax9.set_zticks([])
ax9.set_xlim3d(np.amin(Xposition),np.amax(Xposition))
ax9.set_ylim3d(np.amin(Yposition),np.amax(Yposition))
ax9.set_zlim3d(np.amin(Zposition),np.amax(Zposition))
ax9.set_ylabel(" 512 Mpc/h",fontsize=13,labelpad=-15)

lmin=-2
lmax=7.5
logk=np.linspace(lmin,lmax)
k=10**(logk)
dk=2*np.pi/(a.XSize)
y=k**3*lb.P(k,0)/(2*np.pi**2)
ax10= fig.add_subplot(4,3,10)
ax10.plot(k,y,'k')
section = np.linspace(dk,GridSize*dk,10)
ax10.fill_between(section,section**3*lb.P(section,0)/(2*np.pi**2),color='#191970',alpha=0.2)
ax10.set_yscale('log')
ax10.set_xscale('log')
plt.locator_params(numticks=4)
plt.tick_params(axis='both', which='major', labelsize=10)
plt.tick_params(axis='both', which='minor', labelsize=10)
ax10.set_xlabel('k  (h$Mpc^{-1}$)',fontsize=13,labelpad=-2)
ax10.set_ylabel('$\Delta^2(k)$  ',fontsize=13,labelpad=-2)

logk=np.linspace(lmin,lmax)
k=10**(logk)
dk=2*np.pi/(b.XSize)
y=k**3*lb.P(k,0)/(2*np.pi**2)
ax11= fig.add_subplot(4,3,11)
ax11.plot(k,y,'k')
section = np.linspace(dk,GridSize*dk,10)

ax11.fill_between(section,section**3*lb.P(section,0)/(2*np.pi**2),color='#2c0a33',alpha=0.2)
ax11.set_yscale('log')
ax11.set_xscale('log')
plt.locator_params(numticks=4)
plt.tick_params(axis='both', which='major', labelsize=10)
plt.tick_params(axis='both', which='minor', labelsize=10)
ax11.set_xlabel('k  (h$Mpc^{-1}$)',fontsize=13,labelpad=-2)
#ax11.set_ylabel('$\Delta^2(k)$  ',fontsize=10,labelpad=-2)
#~ plt.title(' Power Spectrum ')
#~ plt.xlabel('k  (h$Mpc^{-1}$)')
#~ plt.ylabel('P(k)  ($h^{-1}Mpc)^3$')

logk=np.linspace(lmin,lmax)
k=10**(logk)
dk=2*np.pi/(c.XSize)
y=k**3*lb.P(k,0)/(2*np.pi**2)
ax12= fig.add_subplot(4,3,12)
ax12.plot(k,y,'k')
section = np.linspace(dk,GridSize*dk,10)
ax12.fill_between(section,section**3*lb.P(section,0)/(2*np.pi**2),color='#2f4f4f',alpha=0.2)
ax12.set_yscale('log')
ax12.set_xscale('log')
plt.locator_params(numticks=4)
plt.tick_params(axis='both', which='major', labelsize=10)
plt.tick_params(axis='both', which='minor', labelsize=10)
#~ plt.title(' Power Spectrum ')
ax12.set_xlabel('k  (h$Mpc^{-1}$)',fontsize=13,labelpad=-2)
#ax12.set_ylabel('$\Delta^2(k)$  ',fontsize=10,labelpad=-2)
plt.tight_layout()

plt.savefig('fig_3d_zeldovich.png',dpi=200, bbox_inches='tight', pad_inches=0)




plt.show()
